### ISSUE TITLE
addon.py fails on certain VOD videos

### ISSUE THREAD

**Issue by stoyansbg** [pesheto/plugin.video.oodnurdtv#2]
Plugin versions tested with: 0.0.9, 0.1.2
OS: Ubuntu 14.04.02 LTS
XBMC version: 12.3 (2:12.3+dfsg1-3ubuntu1)

Some of the pre-recorded videos fail to play. For example, trying to play "Господари на ефира" from the Nova TV "ZAPIS" list fails with the following error:

15:59:07 T:139624018081536   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
     - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
    Error Type: <type 'exceptions.KeyError'>
    Error Contents: (u'VOD-NOVA',)
    Traceback (most recent call last):
      File "/home/stoyansbg/.xbmc/addons/plugin.video.oodnurdtv-master/addon.py", line 178, in <module>
	plugin.run()
      File "/home/stoyansbg/.xbmc/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 332, in run
	items = self._dispatch(self.request.path)
      File "/home/stoyansbg/.xbmc/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 306, in _dispatch
	listitems = view_func(**items)
      File "/home/stoyansbg/.xbmc/addons/plugin.video.oodnurdtv-master/addon.py", line 169, in oshte_final
	plugin.set_resolved_url(my_drundoo.play_live_url(url))
      File "/home/stoyansbg/.xbmc/addons/plugin.video.oodnurdtv-master/resources/drundoo.py", line 121, in play_live_url
	temp = temp[0:x1]+'='+myStat[myTV]+temp[x1:x2]+'&live&'+temp[x2:x3]
    KeyError: (u'VOD-NOVA',)
    -->End of Python script error report<--

15:59:07 T:139625400436672   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.oodnurdtv/oshte_final/http%3A%2F%2Fwww.drundoo.com%2Fplayer%2Fepg_item%2F870798%2F]

Thanks!

**Comment by stoyansbg** [comment]
The commit 1ae3ccd3bcc7e3005dd4ea973cf15b76df57653a on 05/05/2015 fixes the issue. Thanks!
